FROM datamechanics/spark:3.1-latest

ENV PYSPARK_MAJOR_PYTHON_VERSION=3

RUN pip install cassandra-driver

RUN pip install pyspark

COPY precomputed.py .

COPY ./cassandra_client/cassandra_client.py .

CMD ["python3", "precomputed.py"]
