FROM python:3.9-slim

WORKDIR /big_data_project

RUN apt-get update

RUN pip install --upgrade pip

RUN pip install cassandra-driver

RUN pip install requests

COPY read_wikipedia.py .

COPY ./cassandra_client/cassandra_client.py .

ENTRYPOINT ["python3", "read_wikipedia.py"]
