FROM python:3.9-slim

WORKDIR /big_data_project

RUN apt-get update

RUN pip install --upgrade pip

RUN pip install cassandra-driver

RUN pip install flask

RUN pip install flask-restful

COPY ad_hoc_app.py .

COPY ./cassandra_client/cassandra_client.py .

ENTRYPOINT ["python3", "ad_hoc_app.py"]
